title: "Flowing"
subtitle: "Listen, Learn. And More..."
posts_per_page: 5
datetime_format: "%Y-%m-%d %H:%M:%S"

# Social information
twitter_username: "wwwjfy"
github_username: "wwwjfy"
email: "wwwjfy@gmail.com"

encoding: "utf-8"
debug: true