url_root:
title: "Untitled"
subtitle: "Unsubtitled"
posts_per_page: 5
timezone: "Asia/Shanghai"
datetime_format: "%Y-%m-%d %H:%M:%S"

# Social information
twitter_username:
github_username:
email:
google_analytics:

encoding: "utf-8"
debug: true
production: false
